Phase 1-landing
Star-Academy/RezaKalbali pull request #1
Opened 2023-01-26 04:30 UTC by rezakalbaali

2023-01-26 06:36 UTC, milar7 requested changes

2023-01-26 06:36 UTC, milar7 commented on README.md
> +این پروژه با [Angular CLI](https://github.com/angular/angular-cli) نسخه 12.2.17 تولید شده است
موارد اضافه فایل README رو پاک کن و یسری موارد مفید اضافه کن.
از این لینک میتونی استفاده کنی
https://star-academy.github.io/codestar-documents/docs/frontend/phase06-clean-code#readmemd

2023-01-26 06:36 UTC, milar7 commented on src/app/pages/home/home.component.ts
> +type Game = {
استفاده از type اوکیه ولی خیلی پیشنهاد میشه که بجاش از interface استفاده کنی.
یه directory جدید بساز به اسم models و یه فایل game.ts واسش بزار داخلش و interface رو export کن

2023-01-26 06:36 UTC, milar7 commented on src/app/pages/home/home.component.ts
> +  pay: 'free' | 'pay';
بجای این کار یه enum بساز واسش و بزار داخل پوشه enums(باید بسازیش اول) و از اون استفاده کن

2023-01-26 06:36 UTC, milar7 commented on src/app/pages/home/home.component.ts
> +  public games: Array<Game> = [
```typescript
public games: Game[]
```

2023-01-26 06:36 UTC, milar7 commented on src/app/pages/home/home.component.ts
> +  public games: Array<Game> = [
بهتره یا فایل demo-data بسازی و این هارو بزاری داخلش و اینجا فقط ازش استفاده کنی

2023-01-26 06:36 UTC, milar7 commented on src/app/pages/home/home-card/home-card.component.ts
> +  @Input() public price?: number;
بهتره بجای اینکه این همه input بگیری، فقط یدونه input واسه game بگیری بعد ازش استفاده کنی

2023-01-26 06:36 UTC, milar7 commented on src/app/pages/home/home-card/home-card.component.ts
> +  @Input() public img!: string;
```typescript
@Input() public game!: Game;
```

2023-01-26 06:36 UTC, milar7 commented on src/app/pages/home/home-card/home-card.component.ts
> +  public customPrice?: string;
این ترتیب رو واسه property های اول کلاس رعایت کن و با یک فاصله از هم بزار:

1. موارد static یا readonly
2. Inputها
3. Output ها
4. viewChild ها
5. public ها
6. private ها

واسه تابع ها هم اول public ها بعد private ها

2023-01-26 06:36 UTC, milar7 commented on src/app/pages/home/home-card/home-card.component.ts
> +      this.customPrice =
فکر کنم این کار هارو واسه جدا کردن سه رقم سه رقم اعداد قیمت کردی.
کافیه بنویسی:

this.customPrice = this.price.toLocaleString()

2023-01-26 06:36 UTC, milar7 commented on src/app/components/button/button.component.ts
> +
فاصله اضافه پاک بشه

2023-01-26 06:36 UTC, milar7 commented on src/app/components/button/button.component.ts
> +  @Input() public small: boolean = false;
وقتی از boolean میخوای استفاده کنی بهتره اسمش هم معنی بهتری بده مثلا isSmall

2023-01-26 06:36 UTC, milar7 commented on src/app/components/header/avatar/avatar.component.ts
> +  @ViewChild('avatar') public avatar!: ElementRef<HTMLDivElement>;
این خط باید بره بالای کلاس

2023-01-26 06:36 UTC, milar7 commented on src/app/components/header/avatar/avatar.component.ts
> +  public clickOut(event: any): void {
این تابع هم قبل اون یکی تابع

2023-01-26 06:36 UTC, milar7 commented on src/app/pages/home/slideshow/slideshow.component.ts
> +type Slide = {
مثل قبلی

2023-01-26 06:36 UTC, milar7 commented on src/app/pages/home/slideshow/slideshow.component.ts
> +  public slides: Array<Slide> = [
مثل قبلی

2023-01-26 06:36 UTC, milar7 commented on src/app/components/card/card.component.html
> +        [style.--free]="buttonText === 'دانلود رایگان' ? 'green' : 'white'"
این شرط مناسبی نیست.
بهتره یه ورودی isFree واسه card داشته باشی

2023-01-26 06:36 UTC, milar7 commented on src/app/components/card/card.component.html
> +        [src]="img"
این کامنت ربطی بی این خط نداره!.
وقتی میخوای یه تصویر رو به عنوان assets داخل پروژه قرار بدی خیلی بهتره اگه واسه logo هست که فرمتش svg باشه یا اگه جای دیگه میخوای استفاده کنی فرمتش webp باشه که واسه وب optimize شدن.
درسته این عکس ها بعد از سرور میان ولی الان که داخل پروژه هستن باید فرمتشون مناسب باشه.
https://star-academy.github.io/codestar-documents/docs/frontend/phase02-pilot#performance

2023-01-26 06:36 UTC, milar7 commented on src/app/components/card/card.component.html
> +        [src]="img"
هم لوگو رو svg کن هم بقیه رو webp

2023-01-26 06:36 UTC, milar7 commented on src/app/pages/home/slideshow/slideshow.component.scss
> +  .overlay {
بنظرم اگه اینا به حالت افقی همون پایین اسلایدر بود بهتر بود.
آخه اینا بالا پایین میشن ولی اسلاید ها چپ و راست میشن و یکم ممکنه مناسب نباشه

2023-01-26 06:36 UTC, milar7 commented on src/app/pages/home/slideshow/slideshow.component.html
> +      <h2 class="name">{{ slide.alt }}</h2>
این اسمه داخل اسلایدر اصلا ریسپانسیو نیست و اگه صفحه خیلی کوچیک بشه کل اسلایدر رو میگیره

2023-01-26 06:36 UTC, milar7 commented on src/app/components/card/card.component.scss
> +  &:hover {
یه مشکل اساسی که الان پیش میاد.
اگه قرار باشه یسری کانتنت خیلی مهم مثل دکمه خرید یا مبلغ هر بازی رو وقتی کاربر hover میکنه بهش نشون بدی اونوقت تکلیف اونایی که از موبایل یا تبلت استفاده میکنن چی میشه؟
بنظرم یه تغییراتی باید بدی تا این مشکل رفع بشه

2023-01-26 06:56 UTC, rezakalbaali commented on README.md
> +این پروژه با [Angular CLI](https://github.com/angular/angular-cli) نسخه 12.2.17 تولید شده است
موارد اضافه منظور چی هست!

خط 9 یا خطوط آخر فایل که برای راه اندازیه و انگلیسی هست

2023-01-26 08:18 UTC, rezakalbaali commented on src/app/components/card/card.component.html
> +        [style.--free]="buttonText === 'دانلود رایگان' ? 'green' : 'white'"
resolved

2023-01-26 08:21 UTC, rezakalbaali commented on src/app/pages/home/home.component.ts
> +type Game = {
resolved

2023-01-26 08:22 UTC, rezakalbaali commented on src/app/pages/home/home.component.ts
> +  pay: 'free' | 'pay';
resolved

2023-01-26 08:22 UTC, rezakalbaali commented on src/app/pages/home/home.component.ts
> +  public games: Array<Game> = [
resolved

2023-01-26 08:23 UTC, rezakalbaali commented on src/app/pages/home/home.component.ts
> +  public games: Array<Game> = [
resolved

2023-01-26 08:23 UTC, rezakalbaali commented on src/app/pages/home/home-card/home-card.component.ts
> +  @Input() public price?: number;
resolved

2023-01-26 08:23 UTC, rezakalbaali commented on src/app/pages/home/home-card/home-card.component.ts
> +  @Input() public img!: string;
resolved

2023-01-26 08:23 UTC, rezakalbaali commented on src/app/pages/home/home-card/home-card.component.ts
> +      this.customPrice =
resolved

2023-01-26 08:24 UTC, rezakalbaali commented on src/app/components/button/button.component.ts
> +
resolved

2023-01-26 08:24 UTC, rezakalbaali commented on src/app/components/button/button.component.ts
> +  @Input() public small: boolean = false;
resolved

2023-01-26 08:24 UTC, rezakalbaali commented on src/app/components/header/avatar/avatar.component.ts
> +  @ViewChild('avatar') public avatar!: ElementRef<HTMLDivElement>;
resolved

2023-01-26 08:25 UTC, rezakalbaali commented on src/app/components/header/avatar/avatar.component.ts
> +  public clickOut(event: any): void {
resolved

2023-01-26 08:25 UTC, rezakalbaali commented on src/app/pages/home/slideshow/slideshow.component.ts
> +type Slide = {
resolved

2023-01-26 08:27 UTC, rezakalbaali commented on src/app/pages/home/slideshow/slideshow.component.ts
> +  public slides: Array<Slide> = [
resolved

2023-01-26 08:37 UTC, rezakalbaali commented on src/app/pages/home/slideshow/slideshow.component.html
> +      <h2 class="name">{{ slide.alt }}</h2>
ریپانسیو که کلا انجام نشده داخل پروژه بر اساس فیلم دیدم پیاده نشده نکردم
ولی این مورد رو حل میکنم

2023-01-26 10:13 UTC, rezakalbaali commented on src/app/pages/home/slideshow/slideshow.component.html
> +      <h2 class="name">{{ slide.alt }}</h2>
resolved

2023-01-26 10:31 UTC, rezakalbaali commented on src/app/components/card/card.component.scss
> +  &:hover {
با ضربه روی هر کارد مثل هاور عمل میکنه فکر نمی کنم زیاد مشکلی باشه ولی به هر حال شاید مورد پسند نباشه
به هر براش مدیا نوشتم تو صفحه های کوچیک محتوای کارد قابل روئیت باشه

resolved

2023-01-26 10:41 UTC, rezakalbaali commented on src/app/pages/home/slideshow/slideshow.component.scss
> +  .overlay {
resolved

2023-01-26 10:58 UTC, rezakalbaali commented on src/app/components/card/card.component.html
> +        [src]="img"
resolved

2023-01-26 11:04 UTC, rezakalbali commented on src/app/pages/home/home-card/home-card.component.ts
> +  public customPrice?: string;
resolved

2023-01-26 11:33 UTC, rezakalbaali commented on README.md
> +این پروژه با [Angular CLI](https://github.com/angular/angular-cli) نسخه 12.2.17 تولید شده است
resolved

2023-01-26 12:38 UTC, milar7 requested changes

2023-01-26 12:38 UTC, milar7 commented on src/app/app.module.ts
> +  providers: [],
پاک

2023-01-26 12:38 UTC, milar7 commented on src/app/demo-data/game-list.ts
> +export default [
```typescript
export const gameList: GameModel[] =[
```

2023-01-26 12:38 UTC, milar7 commented on src/styles.scss
> +  /* border: 3px solid #f6f7ed; */
پاک

2023-01-26 12:38 UTC, milar7 commented on src/styles.scss
> +  /* border: 3px solid #f6f7ed; */
به هیچ وجه توصیه نمیشه که اسکرول بار default رو تغییر بدی!
خیلی مشکلات واسه مروگرهای دیگه بوجود میاره. بهتره این تیکه رو حذف کنی

2023-01-26 12:38 UTC, milar7 commented on src/styles.scss
> +  /* border: 3px solid #f6f7ed; */
کلا همه قست هایی که نوشتی براش حذف بشه

2023-01-26 12:38 UTC, milar7 commented on src/app/demo-data/game-list.ts
> +export default [
اینو واسه sliderList هم تغییر بده

2023-01-28 06:41 UTC, rezakalbaali commented on src/app/components/card/card.component.scss
> +  &:hover {
resolved

2023-01-28 06:45 UTC, rezakalbaali commented on src/app/demo-data/game-list.ts
> +export default [
resolved

2023-01-28 06:54 UTC, rezakalbaali commented on src/styles.scss
> +  /* border: 3px solid #f6f7ed; */
resolved

2023-01-28 06:55 UTC, rezakalbaali commented on src/styles.scss
> +  /* border: 3px solid #f6f7ed; */
resolved

2023-01-28 06:59 UTC, rezakalbaali commented on src/app/app.module.ts
> +  providers: [],
resolved

2023-01-28 07:14 UTC, milar7 approved these changes

2023-01-28 08:08 UTC, BijanEisapour approved these changes

2023-01-28 08:18 UTC, merged

2023-01-28 08:18 UTC, rezakalbaali commented
merged