Services auth
Star-Academy/RezaKalbali pull request #2
Opened 2023-02-07 13:01 UTC by rezakalbaali

2023-02-08 05:28 UTC, milar7 requested changes

2023-02-08 05:28 UTC, milar7 commented on src/app/components/button/button.component.ts
> +  @Input() public type: "button" | "submit" = "button";
چون بقیه جاها از enum استفاده کردی، ترجیح اینه اینجا هم enum باشه

2023-02-08 05:28 UTC, milar7 commented on src/app/components/button/button.component.ts
>  // @ts-ignore
این واسه چیه؟

2023-02-08 05:28 UTC, milar7 commented on src/app/components/header/avatar/avatar.component.ts
> +  public avatarDisplay: "none" | "block" = "none";
enum DisplayType

2023-02-08 05:28 UTC, milar7 commented on src/app/components/header/avatar/avatar.component.ts
>    public clickOut(event: any): void {
اسم بهتر برای تابع، تا معلوم بشه واسه چه کاری هست

2023-02-08 05:28 UTC, milar7 commented on src/app/components/header/side-menu/side-menu.component.html
> +<div class="container" #sidebar>
اول آیدی بعد کلاس

2023-02-08 05:28 UTC, milar7 commented on src/app/components/header/side-menu/side-menu.component.html
> +<div class="container" #sidebar>
```html
<div #sidebar class="container">
```

2023-02-08 05:28 UTC, milar7 commented on src/app/pages/home/slideshow/slideshow.component.html
> +      <!--      <h2 class="name">{{ slide.alt }}</h2>-->
کامنت پاک بشه

2023-02-08 05:28 UTC, milar7 commented on src/app/pages/profile/profile.component.ts
> +  ngOnInit(): void {}
پاک

2023-02-08 05:28 UTC, milar7 commented on src/app/services/api.service.ts
> +        "var(--color-error)"
این حرکت قابل قبول نیست.
الان داری این قسمت رو وابسته میکنی به syle.css. اگه اون تغییر کنه از کجا متوجه بشیم که بیایم اینجا رو هم عوض کنیم؟
و هم ایجنور مستقیم  کد css مقدار دادن اشتباه هست.

از یه راه دیگه مثلا با enum  هندل کن

2023-02-08 05:55 UTC, rezakalbaali commented on src/app/components/button/button.component.ts
> +  @Input() public type: "button" | "submit" = "button";
resolved

2023-02-08 05:56 UTC, rezakalbaali commented on src/app/components/button/button.component.ts
>  // @ts-ignore
resolved

2023-02-08 06:00 UTC, rezakalbaali commented on src/app/components/header/avatar/avatar.component.ts
> +  public avatarDisplay: "none" | "block" = "none";
resolved

2023-02-08 06:02 UTC, rezakalbaali commented on src/app/components/header/avatar/avatar.component.ts
>    public clickOut(event: any): void {
resolved

2023-02-08 06:04 UTC, rezakalbaali commented on src/app/pages/home/slideshow/slideshow.component.html
> +      <!--      <h2 class="name">{{ slide.alt }}</h2>-->
resolved

2023-02-08 06:04 UTC, rezakalbaali commented on src/app/pages/profile/profile.component.ts
> +  ngOnInit(): void {}
resolved

2023-02-08 06:10 UTC, rezakalbaali commented on src/app/services/api.service.ts
> +        "var(--color-error)"
resolved

2023-02-08 06:18 UTC, rezakalbaali commented on src/app/components/header/side-menu/side-menu.component.html
> +<div class="container" #sidebar>
resolved

2023-02-08 09:26 UTC, milar7 approved these changes

2023-02-13 06:12 UTC, BijanEisapour requested changes

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/app-routing.module.ts
> +import { NgModule } from "@angular/core";
تنظیمات prettier رو درست انجام ندادی
اومد به جای single quote از double quote استفاده کرده

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/button/button.component.html
> +  <i *ngIf="disabled" class="fa-regular fa-loader"></i>
این practice خوبی نیست
یارو از کجا بفهمه این دکمه‌ای که الان disable شده قبلاً چی بوده؟

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/button/button.component.html
> +  [disabled]="disabled"
ترتیب اینا رو رعایت کن

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/button/button.component.html
>    <span>{{ text }}</span>
چرا بین icon و text تفاوت قائل شدی؟
در عمل تو استفاده‌ای که داری ازشون میکنی هیچ تفاوتی وجود نداره
چه تو html چه تو css

چرا از ng-content استفاده نکردی؟

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/button/button.component.scss
> +  width: 100%;
وقتی از display: flex استفاده میکنی، نیازی نیست width: 100% بدی

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/button/button.component.scss
> +    background-color: hsl(0deg 10% 60%);
هیچ جای کد رنگ لخت نداشته باش
واسه تمامِ رنگ‌هایی که استفاده میکنی یه متغیر تو styles.scss درست کن
حتی اگه فقط یه جا داری ازش استفاده میکنی

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/card/card.component.html
> +  <div class="main-content">
از semantic tags استفاده کن
به جای اینکه کلاس main-content بذاری، از تگ main استفاده کن

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/card/card.component.html
> +  <img [src]="img" [alt]="title" />
^

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/card/card.component.html
> +    </span>
چیزی که میشد تو یه خط نوشت رو چرا تو سه خط نوشتی؟

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/card/card.component.scss
> +  flex-direction: column-reverse;
وقتی میتونی ساختار html رو عوض کنی، چرا با css داری ترتیب رو تعیین میکنی؟

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/card/card.component.html
> +<article>
اینجا article معنی نمیده
از div با کلاس card استفاده کن

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/card/card.component.scss
> +  border-radius: 0.8rem;
واسه border-radius متغیر تعریف کن

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/card/card.component.scss
> +  transition-duration: 0.2s;
واسه مدت‌زمان انیمیشن، متغیر تعریف کن

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/card/card.component.scss
> +    transition-duration: 0.4s;
نمیگم

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/card/card.component.scss
> +      direction: ltr;
مگه بقیه چیزا ltr ئن؟

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/card/card.component.scss
> +      text-align: right;
start

بعد اصن نیازه واقعاً ؟

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/card/card.component.scss
> +      -webkit-line-clamp: 1; /* number of lines to show */
کامنتت اضافیه

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/card/card.component.scss
> +      -webkit-line-clamp: 1; /* number of lines to show */
بعد تا جایی که یادم میاد باید display رو هم set میکردی تا این کار کنه

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/card/card.component.scss
> +      color: hsl(0deg 0% 79%);
متغیر
نمیگم

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/card/card.component.scss
> +      -webkit-line-clamp: 2; /* number of lines to show */
نمیگم

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/card/card.component.scss
> +        justify-content: center;
اگه هدفت صرفاً center-alignedکردنه، از display: grid و place-content: center استفاده کن

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/card/card.component.scss
> +    width: 20rem;
تو نباید widthش رو مشخص کنی
باباش باید این کاروا نجام بده
اونم نه این‌شکلی absolute؛ باید با استفاده از flex یا grid باشه

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/card/card.component.scss
> +    flex-direction: row;
تو اینجور مواقع درست نیست از media query استفاده کنی؛ به‌جاش از container query استفاده کن
یه tip of the day هم در موردش بده

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/card/card.component.ts
>    @Input() public isFree: boolean = false;
به‌نظر میرسه ازش استفاده‌ای نکردی

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/card/card.component.ts
>    @Input() public img!: string;
imageSource

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/card/card.component.ts
> +  @Input() public info: string = "";
فرق info با description چیه؟
منی که فقط کد رو دارم میخونم، از لحاظ معنایی و از لحاظ استفاده، متوجه نمیشم چه فرقی دارن
اسم‌ها رو شفاف‌تر بذار

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/card/card.component.ts
>    @Input() public title!: string;
مقدار پیشفرض بهش بده که نیازی نباشه از ! استفاده کنی

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/footer/footer.component.html
> +    <img src="assets/logos/logo.svg" alt="squid game logo" />
اسم فایل رو بهتر بذار
لوگوی چیه دقیقاً ؟
از رو اسمش باید بشه تشخیص داد

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/footer/footer.component.html
> +      انواع بازی برای کنسول های مختلف - دارای فروم و گروه های تخصصی برای هر بازی
از نیم‌فاصله استفاده کن ...
کنسول های => کنسول‌های
گروه های => گروه‌های

اگه کلمۀ فارسیِ جاافتاده‌ای میشه استفاده کرد، بهتره از اون استفاده کنی ...
فروم => انجمن

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/footer/footer.component.html
> +  <div class="banner">
این به‌نظر میرسه اصن جاش تو footer نیست
خودش یه component جداست

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/footer/footer.component.html
> +    <div class="top">
چرا top ؟
مگه bottom هم داریم ؟

حتی اگه داشتیم هم باز بهتره اسمی بذاری که کارکردش رو مشخص کنه نه جایگاهش رو

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/footer/footer.component.html
> +  <div class="main">
وقتی banner رو تبدیل به کامپوننت جدا کردی، یادت باشه این div رو پاک کنی چون اضافی میشه

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/footer/footer.component.html
> +      <div>
این باید section باشه

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/footer/footer.component.html
> +      <div>
بین sectionهای مختلف enter بزن که آدم راحت‌تر بتونه کد رو بخونه

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/footer/footer.component.html
> +        <div class="social">
اسم کامل بذار 
چرا social ؟

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/footer/footer.component.html
> +                src="assets/logos/social/instagram.svg"
اینجا هم اسم بهتر بذار

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/footer/footer.component.html
> +                src="assets/logos/social/telegram-plane.svg"
plane?

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/footer/footer.component.html
> +                src="assets/logos/social/linkedin-in.svg"
in?

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/footer/footer.component.html
> +            alt="github"
چرا همه‌جا اول alt رو نوشتی بعد title، ولی اینجا برعکسه؟

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/footer/footer.component.scss
> +          gap: 1rem;
اینجور مواقع از display: grid استفاده کن

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/footer/footer.component.scss
> +        flex-direction: column;
چه نیازی به این هست؟
اگه پاکش کنی فرقی میکنه؟

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/footer/footer.component.scss
> +        }
خیلی کار اشتباهیه که ورداشتی تو html ساختار رو یه جوری چیدی که این عکس همیشه کنار دکمه باشه
به‌جاش باید تو css و با استفاده از grid-template-areas این کارو انجام بدی

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/footer/footer.component.scss
> +      font-weight: bold;
bold => 700

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/header/avatar/avatar.component.scss
> +  justify-content: center;
نمیگم

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/header/avatar/avatar.component.html
> +      [class.active-avatar]="avatarDisplay === 'block'"
چرا active-avatar ؟
ما که میدونیم این آیکن مربوط به avatar ئه
چرا active خالی نه؟

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/header/avatar/avatar.component.ts
> +    this.authService.logOut().then();
متد رو async کن؛ از await استفاده کنی به جای then

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/header/avatar/avatar.component.ts
> +        : DisplayType.NONE;
به‌جای این کار از boolean استفاده کن 
اسم متغیر رو هم بذار isAvatarVisible یا همچین چیزی

2023-02-13 06:12 UTC, BijanEisapour commented on src/app/components/header/avatar/avatar.component.ts
> +  public onClickOutSide(event: any): void {
event?
any?

2023-02-13 07:25 UTC, rezakalbaali commented on src/app/app-routing.module.ts
> +import { NgModule } from "@angular/core";
`{
  "printWidth": 120,
  "tabWidth": 4,
  "semi": true,
  "singleQuote": true,
  "trailingComma": "es5",`
  
  تنظیم کردم ولی نمیدونم چرا single قبول نمیکنه

2023-02-13 07:35 UTC, rezakalbaali commented on src/app/components/button/button.component.html
> +  <i *ngIf="disabled" class="fa-regular fa-loader"></i>
اینجا فکر میکنم از کلمه مناسبی استفاده نکردم کلمه loading بهتره 👍 
این آیکون فقط قراره زمانی که کلیک میشه و ومیره تو حالت loading جای آیکون اصلی نمایش داده بشه تا نتیجه fetch برگرده

2023-02-13 07:48 UTC, rezakalbaali commented on src/app/components/button/button.component.html
> +  [disabled]="disabled"
resolved

2023-02-13 07:51 UTC, rezakalbaali commented on src/app/components/button/button.component.html
> +  <i *ngIf="disabled" class="fa-regular fa-loader"></i>
resolved

2023-02-13 07:57 UTC, rezakalbaali commented on src/app/components/button/button.component.scss
> +  width: 100%;
اخه خود button رو وقتی داخل ی flex ستونی دیگه استفاده کردم خواستم عرضشو بگیره

2023-02-13 07:59 UTC, rezakalbaali commented on src/app/components/button/button.component.scss
> +    background-color: hsl(0deg 10% 60%);
resolved

2023-02-13 08:00 UTC, rezakalbaali commented on src/app/components/card/card.component.html
> +  <div class="main-content">
resolved

2023-02-13 08:01 UTC, rezakalbaali commented on src/app/components/card/card.component.html
> +  <img [src]="img" [alt]="title" />
resolved

2023-02-13 08:05 UTC, rezakalbaali commented on src/app/components/card/card.component.html
> +    </span>
از چه لحاظ؟! طرفا اینکه افتاده داخل 3 خط یا استفاده از کلاس و...؟

2023-02-13 08:08 UTC, rezakalbaali commented on src/app/components/card/card.component.scss
> +  flex-direction: column-reverse;
```suggestion
  flex-direction: column-reverse;
```

2023-02-13 08:10 UTC, rezakalbaali commented on src/app/components/card/card.component.scss
> +  flex-direction: column-reverse;
چون پایینتر خط 123 با مدیا برای responsive میخوام ترتیب متفاوتی داشته باشه آخر باید تو یکی از ایسن دوجا ترتیب رو تغییر بدم

2023-02-13 08:18 UTC, rezakalbaali commented on src/app/components/card/card.component.html
> +<article>
resolved

2023-02-13 08:31 UTC, rezakalbaali commented on src/app/components/card/card.component.scss
> +  border-radius: 0.8rem;
resolved

2023-02-13 08:39 UTC, rezakalbaali commented on src/app/components/card/card.component.scss
> +  transition-duration: 0.2s;
resolved

2023-02-13 09:50 UTC, rezakalbaali commented on src/app/components/card/card.component.scss
> +    transition-duration: 0.4s;
resolved

2023-02-13 09:53 UTC, rezakalbaali commented on src/app/components/card/card.component.scss
> +      direction: ltr;
بقیه چیزا rtl هستند ولی اینجا چون title بازی که انگلیسیه قرار میگیره ltr کردم که وقتی `text-overflow: ellipsis;` میزنم از سمت راست حذف کنه و سه نقطه بزاره

2023-02-13 10:00 UTC, rezakalbaali commented on src/app/components/card/card.component.scss
> +      text-align: right;
جوابِ همون کامنت قبلی

2023-02-13 10:04 UTC, rezakalbaali commented on src/app/components/card/card.component.scss
> +      direction: ltr;
![image](https://user-images.githubusercontent.com/50655453/218428660-1c5ac6cd-c709-4515-9363-007118ce909c.png)

2023-02-13 10:05 UTC, rezakalbaali commented on src/app/components/card/card.component.scss
> +      direction: ltr;
![image](https://user-images.githubusercontent.com/50655453/218428922-285a2aaa-c930-4578-9be9-7efdb561ffe4.png)

2023-02-13 10:09 UTC, rezakalbaali commented on src/app/components/card/card.component.scss
> +      -webkit-line-clamp: 1; /* number of lines to show */
نه بدون display کار میکنه

2023-02-13 10:09 UTC, rezakalbaali commented on src/app/components/card/card.component.scss
> +      -webkit-line-clamp: 1; /* number of lines to show */
useless comment resolved

2023-02-13 11:03 UTC, rezakalbaali commented on src/app/components/card/card.component.scss
> +      color: hsl(0deg 0% 79%);
resolved

2023-02-13 11:05 UTC, rezakalbaali commented on src/app/components/card/card.component.scss
> +      -webkit-line-clamp: 2; /* number of lines to show */
همون مورد  `text-overflow: ellipsis` که بالاتر گفتم

2023-02-13 11:07 UTC, rezakalbaali commented on src/app/components/card/card.component.scss
> +        justify-content: center;
resolved

2023-02-13 11:08 UTC, rezakalbaali commented on src/app/components/card/card.component.scss
> +    width: 20rem;
resolved

2023-02-14 11:51 UTC, rezakalbaali commented on src/app/components/card/card.component.ts
>    @Input() public isFree: boolean = false;
resolved

2023-02-14 11:53 UTC, rezakalbaali commented on src/app/components/card/card.component.ts
>    @Input() public img!: string;
resolved

2023-02-14 11:55 UTC, rezakalbaali commented on src/app/components/card/card.component.ts
> +  @Input() public info: string = "";
resolved

2023-02-14 12:01 UTC, rezakalbaali commented on src/app/components/card/card.component.ts
>    @Input() public title!: string;
resolved

2023-02-14 12:02 UTC, rezakalbaali commented on src/app/components/footer/footer.component.html
> +    <img src="assets/logos/logo.svg" alt="squid game logo" />
resolved

2023-02-14 12:16 UTC, rezakalbaali commented on src/app/components/footer/footer.component.html
> +        <div class="social">
resolved

2023-02-14 12:17 UTC, rezakalbaali commented on src/app/components/footer/footer.component.html
> +                src="assets/logos/social/instagram.svg"
resolved

2023-02-14 12:17 UTC, rezakalbaali commented on src/app/components/footer/footer.component.html
> +                src="assets/logos/social/telegram-plane.svg"
resolved

2023-02-14 12:17 UTC, rezakalbaali commented on src/app/components/footer/footer.component.html
> +                src="assets/logos/social/linkedin-in.svg"
resolved

2023-02-14 12:17 UTC, rezakalbaali commented on src/app/components/footer/footer.component.html
> +            alt="github"
resolved

2023-02-14 12:21 UTC, rezakalbaali commented on src/app/components/footer/footer.component.scss
> +          gap: 1rem;
resolved

2023-02-14 12:22 UTC, rezakalbaali commented on src/app/components/footer/footer.component.scss
> +        flex-direction: column;
resolved

2023-02-14 12:27 UTC, rezakalbaali commented on src/app/components/header/avatar/avatar.component.scss
> +  justify-content: center;
resolved

2023-02-14 12:43 UTC, rezakalbaali commented on src/app/components/header/avatar/avatar.component.html
> +      [class.active-avatar]="avatarDisplay === 'block'"
resolved

2023-02-14 12:45 UTC, rezakalbaali commented on src/app/components/header/avatar/avatar.component.ts
> +    this.authService.logOut().then();
resolved

2023-02-14 12:53 UTC, rezakalbaali commented on src/app/components/header/avatar/avatar.component.ts
> +        : DisplayType.NONE;
resolved

2023-02-15 05:55 UTC, rezakalbaali commented on src/app/components/footer/footer.component.html
> +      انواع بازی برای کنسول های مختلف - دارای فروم و گروه های تخصصی برای هر بازی
resolved

2023-02-15 07:08 UTC, rezakalbaali commented on src/app/components/footer/footer.component.html
> +  <div class="banner">
resolved

2023-02-15 07:08 UTC, rezakalbaali commented on src/app/components/footer/footer.component.html
> +    <div class="top">
resolved

2023-02-15 07:18 UTC, rezakalbaali commented on src/app/components/footer/footer.component.html
> +  <div class="main">
]چون میخوام ی تعداد style  مشترک به محتوای داخلش بدم بازم نیار دارم

2023-02-15 07:19 UTC, rezakalbaali commented on src/app/components/footer/footer.component.html
> +      <div>
resolved

2023-02-15 07:20 UTC, rezakalbaali commented on src/app/components/footer/footer.component.html
> +      <div>
resolved

2023-02-15 09:51 UTC, rezakalbali commented on src/app/components/header/avatar/avatar.component.ts
> +  public onClickOutSide(event: any): void {
resolved

2023-02-15 09:52 UTC, rezakalbaali commented on src/app/components/footer/footer.component.scss
> +      font-weight: bold;
resolved but why??

2023-02-15 10:01 UTC, rezakalbaali commented on src/app/components/footer/footer.component.scss
> +        }
resolved

2023-02-15 10:04 UTC, rezakalbaali commented on src/app/components/footer/footer.component.html
> +  <div class="main">
خواستم به جای margin ی کانتینر دیگه باشه که بجاش به اون padding بدم

2023-02-15 10:04 UTC, rezakalbaali commented on src/app/components/card/card.component.scss
> +    flex-direction: row;
resolved

2023-02-15 10:05 UTC, rezakalbaali commented on src/app/components/card/card.component.scss
> +    flex-direction: row;
ی  ToTD هم اوکی میکنم

2023-02-15 10:06 UTC, rezakalbaali commented on src/app/app-routing.module.ts
> +import { NgModule } from "@angular/core";
resolved

2023-02-16 05:41 UTC, BijanEisapour approved these changes

2023-02-16 05:41 UTC, BijanEisapour commented on .prettierrc
> +  "tabWidth": 2,
از الان به 4 عادت کن چون تو پروژه اصلی از 4 استفاده میکنیم
اینو برگردون به همون 4 که بود و تمام فایل‌ها رو reformat کن

2023-02-16 05:41 UTC, BijanEisapour commented on src/app/components/footer/footer.component.html
> +  <div class="main">
به خودِ footer بده، چرا یه div اضافه ساختی؟

2023-02-16 05:41 UTC, BijanEisapour commented on src/app/components/footer/footer.component.scss
> +        }
بدتر شده

2023-02-16 05:41 UTC, BijanEisapour commented on src/app/pages/auth/auth.component.html
> +  <form (ngSubmit)="formSubmitHandler()" [formGroup]="userForm">
ترتیب

2023-02-16 05:41 UTC, BijanEisapour commented on src/app/pages/auth/auth.component.html
> +    <img src="../../../assets/logos/squid-game-logo.svg" alt="squid game logo" />
آدرس رو absolute بده

2023-02-16 05:41 UTC, BijanEisapour commented on src/app/pages/auth/auth.component.html
> +        >
ظاهرش بهم ریخته
بقیه جاهای این فایل هم همین شکلیه
درستشون کن

```html
<span class="info" *ngIf="isSubmitted && userForm.controls.username.status === 'INVALID'">
    مقدار وارد شده نا معتبر است
</span>
```

2023-02-16 05:41 UTC, BijanEisapour commented on src/app/pages/auth/auth.component.html
> +        <input type="password" name="password" formControlName="password" minlength="8" maxlength="32" />
واسه ورود نباید validation بذاری

2023-02-16 05:41 UTC, BijanEisapour commented on src/app/pages/auth/auth.component.scss
> +      gap: 0.6rem;
یعنی واقعاً اون یه پیکسل انقد مهمه که حتماً باید بنویسید 0.6 به جای 0.5 ؟

2023-02-16 05:41 UTC, BijanEisapour commented on src/app/pages/auth/auth.component.scss
> +      flex-direction: row;
به‌صورت پیش‌فرض مقدارش همینه 
نیازی نیست بنویسی

2023-02-16 05:41 UTC, BijanEisapour commented on src/app/pages/home/features/features.component.scss
> +  container: features / inline-size;
استفاده‌ای هم کردی از این؟

2023-02-16 05:41 UTC, BijanEisapour commented on src/app/pages/home/features/features.component.scss
> +    font-weight: bold;
700
همه جا رو درست کن

2023-02-16 05:41 UTC, BijanEisapour commented on src/app/pages/home/features/features.component.ts
> +  ngOnInit(): void {}
x

2023-02-16 05:59 UTC, rezakalbaali commented on src/app/pages/auth/auth.component.scss
> +      flex-direction: row;
نبود ولی به کل فرم دادم و از اینجا حذف کردم

2023-02-16 06:03 UTC, rezakalbaali commented on src/app/pages/auth/auth.component.html
> +        <input type="password" name="password" formControlName="password" minlength="8" maxlength="32" />
resolved

2023-02-16 06:14 UTC, rezakalbaali commented on .prettierrc
> +  "tabWidth": 2,
resolved

2023-02-16 07:06 UTC, rezakalbaali commented on src/app/components/footer/footer.component.scss
> +        }
resolved

2023-02-16 08:39 UTC, rezakalbaali commented on src/app/components/button/button.component.html
>    <span>{{ text }}</span>
resolved

2023-02-16 08:53 UTC, merged

2023-02-16 08:53 UTC, rezakalbaali commented
merged