Search page
Star-Academy/RezaKalbali pull request #5
Opened 2023-02-27 08:53 UTC by rezakalbaali

2023-02-28 13:11 UTC, milar7 requested changes

2023-02-28 13:11 UTC, milar7 commented on src/app/components/header/header.component.html
> +            <button class="login-or-register-btn" (click)="onClickLogInButton()">ورود / ثبت نام</button>
نیازی به onClick نیست.
از routerLink استفاده کن

2023-02-28 13:11 UTC, milar7 commented on src/app/components/header/header.component.html
> +            <button class="login-or-register-btn" (click)="onClickLogInButton()">ورود / ثبت نام</button>
```html
<button [routerLink]="'/auth'"> text</button>
```

2023-02-28 13:11 UTC, milar7 commented on src/app/components/header/search-box/search-box.component.ts
> +    public constructor(public gameService: GameService) {
بنظر gameService میتونه private باشه

2023-02-28 13:11 UTC, milar7 commented on src/app/components/header/header.component.ts
>      public async onClickLogInButton(): Promise<void> {
حذف

2023-02-28 13:11 UTC, milar7 commented on src/app/models/game-search-params.ts
> +    search_term?: string;
camel case

2023-02-28 13:11 UTC, milar7 commented on src/app/models/game-search-params.ts
> +    only_free?: string;
camel case

2023-02-28 13:11 UTC, milar7 commented on src/app/components/header/search-box/search-box.component.ts
> +
```typescript
const queryParams: GameSearchParams = {search_term: this.searchTerm,
 page: 1,
order:this.gameService.gameSearchParams.order?? this.OrderTypes.POPULER
};

      
```

2023-02-28 13:11 UTC, milar7 commented on src/app/components/header/search-box/search-box.component.ts
> +            queryParams.order = 'popular';
این popular بنظر میتونه enum بشه. اگه نه یه private readonly بالای کلاس تعریف کن

2023-02-28 13:11 UTC, milar7 commented on src/app/components/pagination/pagination.component.html
> +        <li *ngIf="index + 1 <= activePage + 4 && index + 1 >= activePage - 4">
یه pipe واسه این بساز که activePage و index رو بگیره و boolean برگردونه

2023-02-28 13:11 UTC, milar7 commented on src/app/models/game.ts
> +    freetogame_profile_url: string;
گفتم

2023-02-28 13:11 UTC, milar7 commented on src/app/models/game.ts
> +    game_url: string;
گفتم

2023-02-28 13:11 UTC, milar7 commented on src/app/pages/home/home-card/home-card.component.ts
> +    @Input() public skeletonIsActive: boolean = false;
isSkeletonActive

2023-03-01 03:53 UTC, BijanEisapour approved these changes

2023-03-01 05:21 UTC, rezakalbaali commented on src/app/components/header/header.component.html
> +            <button class="login-or-register-btn" (click)="onClickLogInButton()">ورود / ثبت نام</button>
resolved

2023-03-01 05:22 UTC, rezakalbaali commented on src/app/components/header/search-box/search-box.component.ts
> +    public constructor(public gameService: GameService) {
resolved

2023-03-01 05:22 UTC, rezakalbaali commented on src/app/components/header/header.component.ts
>      public async onClickLogInButton(): Promise<void> {
resolved

2023-03-01 05:26 UTC, rezakalbaali commented on src/app/models/game-search-params.ts
> +    search_term?: string;
resolved

2023-03-01 05:30 UTC, rezakalbaali commented on src/app/components/header/search-box/search-box.component.ts
> +
خواستم بببینم اگه مقدار قبلی هست کلا این کلید رو دیگه اضافه نکنم
با این حال تغییر دادم به حالتی که گفتی

2023-03-01 05:31 UTC, rezakalbaali commented on src/app/components/header/search-box/search-box.component.ts
> +            queryParams.order = 'popular';
resolved

2023-03-01 05:35 UTC, rezakalbaali commented on src/app/models/game.ts
> +    freetogame_profile_url: string;
resolved

2023-03-01 05:37 UTC, rezakalbaali commented on src/app/pages/home/home-card/home-card.component.ts
> +    @Input() public skeletonIsActive: boolean = false;
resolved

2023-03-01 05:37 UTC, rezakalbaali commented on src/app/models/game.ts
> +    game_url: string;
resolved

2023-03-01 05:38 UTC, rezakalbaali commented on src/app/components/header/search-box/search-box.component.ts
> +
resolved

2023-03-01 05:38 UTC, rezakalbaali commented on src/app/models/game-search-params.ts
> +    only_free?: string;
resolved

2023-03-01 05:55 UTC, rezakalbaali commented on src/app/components/pagination/pagination.component.html
> +        <li *ngIf="index + 1 <= activePage + 4 && index + 1 >= activePage - 4">
resolved

2023-03-01 06:18 UTC, milar7 approved these changes

2023-03-01 06:18 UTC, merged